### PR TITLE
Added test to validate batch request/response payloads

### PR DESCRIPTION
**Pull request by mikepizzo**
### Description
*This pull request fixes issue adds a test to validate batch request/response payloads.*  

### Checklist (Uncheck if it is not completed)
- [ x ] *Test cases added*
- [ x ] *Build and test with one-click build and test script passed*

### CODE REVIEW

**Comment by robertmclaws** [comment]
`MimePayloadTest` is failing for me on AspNet Classic, and all the batching tests are still failing for me on every AspNetCore permutation. Does something need to be configured differently?

**Comment by mikepizzo** [comment]
I'll take a look. Are they failing if you run individually or just if you run together with the other tests?

**Comment by robertmclaws** [comment]
AspNetCore is failing individually and separately. MimePayloadTest on AspNet Classic passed by itself.

**Comment by mikepizzo** [comment]
Yep; MimePayloadTest is failing when run in after JsonPayloadTest because the data isn't reset between tests so the inserts fail because the records already exist. I think we need to change the test server to reset each time, as I notice a bunch of other tests failing when run in sequence but passing when run individually.

The Aspnetcore batch tests were failing on the initial GET because the baseUri was not set properly for those tests. I've fixed that, but am now getting a bad format error on all of the batch tests (not just the ones I added). I don't think that has anything to do with my changes, but haven't had a chance to track whether that's due to the way the aspnetcore test service is set up or the aspnetcore code itself. Will try and get dig deeper this week.

**Pull request merged**
