### PR TITLE
Inner service instance injection.

### PR DESCRIPTION
**Pull request by rayao**
Inner service instance injection. via public settable property.
Remove EnsureCommitted & IsCommitted.

### CODE REVIEW

**Comment by rayao** [comment]
I'll wait till the other pull request checked in.

**Comment by lewischeng-ms** [comment]
@rayao Thanks. All other pull requests have been merged.

**Comment by rayao** [comment]
@lewischeng-ms Also, of course I won't push without your review and a "GO" directive. :)

**Comment by lewischeng-ms** [comment]
@rayao Would you please resend a PR based on the latest branch? GitHub seems to mess up the PR... Thanks.

**Pull request closed without merging**
